In [1]:
# boolian masking is the fast and efficient querrying in numpy

In [2]:
import pandas as pd
df=pd.read_csv("olympics.csv",index_col=0,skiprows=1)
for col in df.columns:
    if col[:2]=="01":
        df.rename(columns={col:"gold"+col[4:]} ,inplace=True)
    if col[:2]=="02":
        df.rename(columns={col:"silver"+col[4:]} ,inplace=True)
    if col[:2]=="03":
        df.rename(columns={col:"bronze"+col[4:]} ,inplace=True)
    if col[:2]=="01":
        df.rename(columns={col:"#"+col[4:]} ,inplace=True)
    
df.head()

,№ Summer,gold,silver,bronze,Total,№ Winter,gold.1,silver.1,bronze.1,Total.1,№ Games,gold.2,silver.2,bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [3]:
df["gold"]>10

Afghanistan (AFG)                               False
Algeria (ALG)                                   False
Argentina (ARG)                                  True
Armenia (ARM)                                   False
Australasia (ANZ) [ANZ]                         False
                                                ...
Independent Olympic Participants (IOP) [IOP]    False
Zambia (ZAM) [ZAM]                              False
Zimbabwe (ZIM) [ZIM]                            False
Mixed team (ZZX) [ZZX]                          False
Totals                                           True
Name: gold, Length: 147, dtype: bool

In [4]:
only_gold=df.where(df['gold']>0)
only_gold

,№ Summer,gold,silver,bronze,Total,№ Winter,gold.1,silver.1,bronze.1,Total.1,№ Games,gold.2,silver.2,bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Independent Olympic Participants (IOP) [IOP],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia (ZAM) [ZAM],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe (ZIM) [ZIM],12.0,3.0,4.0,1.0,8.0,1.0,0.0,0.0,0.0,0.0,13.0,3.0,4.0,1.0,8.0
Mixed team (ZZX) [ZZX],3.0,8.0,5.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,4.0,17.0
Totals,27.0,4809.0,4775.0,5130.0,14714.0,22.0,959.0,958.0,948.0,2865.0,49.0,5768.0,5733.0,6078.0,17579.0

In [5]:
only_gold["gold"].count()

100

In [6]:
df['gold'].count()

147

In [7]:
len(df[(df['gold']>0) & (df["gold.1"]>10)])

18

In [10]:
k=df['gold'][df['gold.1']>3]
k

Australia (AUS) [AUS] [Z]               139
Austria (AUT)                            18
Belarus (BLR)                            12
Canada (CAN)                             59
China (CHN) [CHN]                       201
Croatia (CRO)                             6
Czech Republic (CZE) [CZE]               14
Estonia (EST)                             9
Finland (FIN)                           101
France (FRA) [O] [P] [Z]                202
Germany (GER) [GER] [Z]                 174
United Team of Germany (EUA) [EUA]       28
East Germany (GDR) [GDR]                153
West Germany (FRG) [FRG]                 56
Great Britain (GBR) [GBR] [Z]           236
Italy (ITA) [M] [S]                     198
Japan (JPN)                             130
South Korea (KOR)                        81
Netherlands (NED) [Z]                    77
Norway (NOR) [Q]                         56
Poland (POL)                             64
Russia (RUS) [RUS]                      132
Soviet Union (URS) [URS]                395
Unified Team (EUN) [EUN]                 45
Sweden (SWE) [Z]                        143
Switzerland (SUI)                        47
United States (USA) [P] [Q] [R] [Z]     976
Totals                                 4809
Name: gold, dtype: int64